[package]
name = "vehicle"
version = "0.1.0"
edition = "2021"
license="MIT"
description="Vehicle Calculation Library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"